// stage2/react/src/pages/SignUp.jsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { signup } from '../utils/auth';
import toast from 'react-hot-toast';

const Signup = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: ''
  });
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    // Clear error for this field
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const validateForm = () => {
    const newErrors = {};

    // Name validation
    if (!formData.name) {
      newErrors.name = 'Name is required';
    } else if (formData.name.length < 2) {
      newErrors.name = 'Name must be at least 2 characters';
    }

    // Email validation
    if (!formData.email) {
      newErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Please enter a valid email address';
    }

    // Password validation
    if (!formData.password) {
      newErrors.password = 'Password is required';
    } else if (formData.password.length < 6) {
      newErrors.password = 'Password must be at least 6 characters';
    }

    // Confirm password validation
    if (!formData.confirmPassword) {
      newErrors.confirmPassword = 'Please confirm your password';
    } else if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = 'Passwords do not match';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      toast.error('Please fix the errors in the form');
      return;
    }

    setLoading(true);

    try {
      await signup(formData.name, formData.email, formData.password);
      toast.success('Account created successfully! Welcome aboard.');
      navigate('/dashboard');
    } catch (error) {
      toast.error(error.message || 'Signup failed. Please try again.');
      setErrors({ general: error.message });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-page">
      <div className="wrapper">
        <div className="auth-container">
          <div className="auth-box">
            <h1 className="auth-title">Create Account</h1>
            <p className="auth-subtitle">Start managing your tickets today</p>

            {errors.general && (
              <div className="error-banner">
                {errors.general}
              </div>
            )}

            <form onSubmit={handleSubmit} className="auth-form" noValidate>
              <div className="form-group">
                <label htmlFor="name">
                  Full Name <span className="required">*</span>
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  className={errors.name ? 'error' : ''}
                  placeholder="John Doe"
                  aria-describedby={errors.name ? 'name-error' : undefined}
                />
                {errors.name && (
                  <span className="error-message" id="name-error" role="alert">
                    {errors.name}
                  </span>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="email">
                  Email Address <span className="required">*</span>
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  className={errors.email ? 'error' : ''}
                  placeholder="you@example.com"
                  aria-describedby={errors.email ? 'email-error' : undefined}
                />
                {errors.email && (
                  <span className="error-message" id="email-error" role="alert">
                    {errors.email}
                  </span>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="password">
                  Password <span className="required">*</span>
                </label>
                <input
                  type="password"
                  id="password"
                  name="password"
                  value={formData.password}
                  onChange={handleChange}
                  className={errors.password ? 'error' : ''}
                  placeholder="Minimum 6 characters"
                  aria-describedby={errors.password ? 'password-error' : undefined}
                />
                {errors.password && (
                  <span className="error-message" id="password-error" role="alert">
                    {errors.password}
                  </span>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="confirmPassword">
                  Confirm Password <span className="required">*</span>
                </label>
                <input
                  type="password"
                  id="confirmPassword"
                  name="confirmPassword"
                  value={formData.confirmPassword}
                  onChange={handleChange}
                  className={errors.confirmPassword ? 'error' : ''}
                  placeholder="Re-enter your password"
                  aria-describedby={errors.confirmPassword ? 'confirmPassword-error' : undefined}
                />
                {errors.confirmPassword && (
                  <span className="error-message" id="confirmPassword-error" role="alert">
                    {errors.confirmPassword}
                  </span>
                )}
              </div>

              <button
                type="submit"
                className="btn btn-primary btn-block"
                disabled={loading}
              >
                {loading ? 'Creating Account...' : 'Sign Up'}
              </button>
            </form>

            <div className="auth-footer">
              <p>
                Already have an account?{' '}
                <Link to="/auth/login" className="auth-link">
                  Login here
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Signup;

// stage2/vue/src/views/SignUp.vue
<template>
  <div class="auth-page">
    <div class="wrapper">
      <div class="auth-container">
        <div class="auth-box">
          <h1 class="auth-title">Create Account</h1>
          <p class="auth-subtitle">Start managing your tickets today</p>

          <div v-if="errors.general" class="error-banner">
            {{ errors.general }}
          </div>

          <form @submit.prevent="handleSubmit" class="auth-form" novalidate>
            <div class="form-group">
              <label for="name">
                Full Name <span class="required">*</span>
              </label>
              <input
                type="text"
                id="name"
                v-model="formData.name"
                :class="{ error: errors.name }"
                placeholder="John Doe"
                :aria-describedby="errors.name ? 'name-error' : undefined"
                @blur="validateField('name')"
              />
              <span 
                v-if="errors.name" 
                class="error-message" 
                id="name-error" 
                role="alert"
              >
                {{ errors.name }}
              </span>
            </div>

            <div class="form-group">
              <label for="email">
                Email Address <span class="required">*</span>
              </label>
              <input
                type="email"
                id="email"
                v-model="formData.email"
                :class="{ error: errors.email }"
                placeholder="you@example.com"
                :aria-describedby="errors.email ? 'email-error' : undefined"
                @blur="validateField('email')"
              />
              <span 
                v-if="errors.email" 
                class="error-message" 
                id="email-error" 
                role="alert"
              >
                {{ errors.email }}
              </span>
            </div>

            <div class="form-group">
              <label for="password">
                Password <span class="required">*</span>
              </label>
              <input
                type="password"
                id="password"
                v-model="formData.password"
                :class="{ error: errors.password }"
                placeholder="Minimum 6 characters"
                :aria-describedby="errors.password ? 'password-error' : undefined"
                @blur="validateField('password')"
              />
              <span 
                v-if="errors.password" 
                class="error-message" 
                id="password-error" 
                role="alert"
              >
                {{ errors.password }}
              </span>
            </div>

            <div class="form-group">
              <label for="confirmPassword">
                Confirm Password <span class="required">*</span>
              </label>
              <input
                type="password"
                id="confirmPassword"
                v-model="formData.confirmPassword"
                :class="{ error: errors.confirmPassword }"
                placeholder="Re-enter your password"
                :aria-describedby="errors.confirmPassword ? 'confirmPassword-error' : undefined"
                @blur="validateField('confirmPassword')"
              />
              <span 
                v-if="errors.confirmPassword" 
                class="error-message" 
                id="confirmPassword-error" 
                role="alert"
              >
                {{ errors.confirmPassword }}
              </span>
            </div>

            <button
              type="submit"
              class="btn btn-primary btn-block"
              :disabled="loading"
            >
              {{ loading ? 'Creating Account...' : 'Sign Up' }}
            </button>
          </form>

          <div class="auth-footer">
            <p>
              Already have an account?
              <router-link to="/auth/login" class="auth-link">
                Login here
              </router-link>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { signup } from '../utils/auth'

const router = useRouter()
const toast = useToast()

const formData = reactive({
  name: '',
  email: '',
  password: '',
  confirmPassword: ''
})

const errors = reactive({
  name: '',
  email: '',
  password: '',
  confirmPassword: '',
  general: ''
})

const loading = ref(false)

const validateField = (field) => {
  if (field === 'name') {
    if (!formData.name) {
      errors.name = 'Name is required'
    } else if (formData.name.length < 2) {
      errors.name = 'Name must be at least 2 characters'
    } else {
      errors.name = ''
    }
  }

  if (field === 'email') {
    if (!formData.email) {
      errors.email = 'Email is required'
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      errors.email = 'Please enter a valid email address'
    } else {
      errors.email = ''
    }
  }

  if (field === 'password') {
    if (!formData.password) {
      errors.password = 'Password is required'
    } else if (formData.password.length < 6) {
      errors.password = 'Password must be at least 6 characters'
    } else {
      errors.password = ''
    }
  }

  if (field === 'confirmPassword') {
    if (!formData.confirmPassword) {
      errors.confirmPassword = 'Please confirm your password'
    } else if (formData.password !== formData.confirmPassword) {
      errors.confirmPassword = 'Passwords do not match'
    } else {
      errors.confirmPassword = ''
    }
  }
}

const validateForm = () => {
  validateField('name')
  validateField('email')
  validateField('password')
  validateField('confirmPassword')
  
  return !errors.name && !errors.email && !errors.password && !errors.confirmPassword
}

const handleSubmit = async () => {
  if (!validateForm()) {
    toast.error('Please fix the errors in the form')
    return
  }

  loading.value = true
  errors.general = ''

  try {
    await signup(formData.name, formData.email, formData.password)
    toast.success('Account created successfully! Welcome aboard.')
    router.push('/dashboard')
  } catch (error) {
    toast.error(error.message || 'Signup failed. Please try again.')
    errors.general = error.message
  } finally {
    loading.value = false
  }
}
</script>
