// stage2/vue/src/views/Login.vue
<template>
  <div class="auth-page">
    <div class="wrapper">
      <div class="auth-container">
        <div class="auth-box">
          <h1 class="auth-title">Welcome Back</h1>
          <p class="auth-subtitle">Login to manage your tickets</p>

          <div v-if="errors.general" class="error-banner">
            {{ errors.general }}
          </div>

          <form @submit.prevent="handleSubmit" class="auth-form" novalidate>
            <div class="form-group">
              <label for="email">
                Email Address <span class="required">*</span>
              </label>
              <input
                type="email"
                id="email"
                v-model="formData.email"
                :class="{ error: errors.email }"
                placeholder="you@example.com"
                :aria-describedby="errors.email ? 'email-error' : undefined"
                @blur="validateField('email')"
              />
              <span 
                v-if="errors.email" 
                class="error-message" 
                id="email-error" 
                role="alert"
              >
                {{ errors.email }}
              </span>
            </div>

            <div class="form-group">
              <label for="password">
                Password <span class="required">*</span>
              </label>
              <input
                type="password"
                id="password"
                v-model="formData.password"
                :class="{ error: errors.password }"
                placeholder="Enter your password"
                :aria-describedby="errors.password ? 'password-error' : undefined"
                @blur="validateField('password')"
              />
              <span 
                v-if="errors.password" 
                class="error-message" 
                id="password-error" 
                role="alert"
              >
                {{ errors.password }}
              </span>
            </div>

            <button
              type="submit"
              class="btn btn-primary btn-block"
              :disabled="loading"
            >
              {{ loading ? 'Logging in...' : 'Login' }}
            </button>
          </form>

          <div class="auth-footer">
            <p>
              Don't have an account?
              <router-link to="/auth/signup" class="auth-link">
                Sign up here
              </router-link>
            </p>
          </div>

          <div class="auth-demo">
            <p class="demo-title">Demo Credentials:</p>
            <p class="demo-creds">
              Email: <code>demo@ticket.app</code><br />
              Password: <code>password123</code>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { login } from '../utils/auth'

const router = useRouter()
const toast = useToast()

const formData = reactive({
  email: '',
  password: ''
})

const errors = reactive({
  email: '',
  password: '',
  general: ''
})

const loading = ref(false)

const validateField = (field) => {
  if (field === 'email') {
    if (!formData.email) {
      errors.email = 'Email is required'
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      errors.email = 'Please enter a valid email address'
    } else {
      errors.email = ''
    }
  }

  if (field === 'password') {
    if (!formData.password) {
      errors.password = 'Password is required'
    } else if (formData.password.length < 6) {
      errors.password = 'Password must be at least 6 characters'
    } else {
      errors.password = ''
    }
  }
}

const validateForm = () => {
  validateField('email')
  validateField('password')
  return !errors.email && !errors.password
}

const handleSubmit = async () => {
  if (!validateForm()) {
    toast.error('Please fix the errors in the form')
    return
  }

  loading.value = true
  errors.general = ''

  try {
    await login(formData.email, formData.password)
    toast.success('Login successful! Welcome back.')
    router.push('/dashboard')
  } catch (error) {
    toast.error(error.message || 'Login failed. Please try again.')
    errors.general = error.message
  } finally {
    loading.value = false
  }
}
</script>

// react/src/pages/Login.jsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { login } from '../utils/auth';
import toast from 'react-hot-toast';

const Login = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    email: '',
    password: ''
  });
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    // Clear error for this field
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const validateForm = () => {
    const newErrors = {};

    // Email validation
    if (!formData.email) {
      newErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Please enter a valid email address';
    }

    // Password validation
    if (!formData.password) {
      newErrors.password = 'Password is required';
    } else if (formData.password.length < 6) {
      newErrors.password = 'Password must be at least 6 characters';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateForm()) {
      toast.error('Please fix the errors in the form');
      return;
    }

    setLoading(true);

    try {
      await login(formData.email, formData.password);
      toast.success('Login successful! Welcome back.');
      navigate('/dashboard');
    } catch (error) {
      toast.error(error.message || 'Login failed. Please try again.');
      setErrors({ general: error.message });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="auth-page">
      <div className="wrapper">
        <div className="auth-container">
          <div className="auth-box">
            <h1 className="auth-title">Welcome Back</h1>
            <p className="auth-subtitle">Login to manage your tickets</p>

            {errors.general && (
              <div className="error-banner">
                {errors.general}
              </div>
            )}

            <form onSubmit={handleSubmit} className="auth-form" noValidate>
              <div className="form-group">
                <label htmlFor="email">
                  Email Address <span className="required">*</span>
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  className={errors.email ? 'error' : ''}
                  placeholder="you@example.com"
                  aria-describedby={errors.email ? 'email-error' : undefined}
                />
                {errors.email && (
                  <span className="error-message" id="email-error" role="alert">
                    {errors.email}
                  </span>
                )}
              </div>

              <div className="form-group">
                <label htmlFor="password">
                  Password <span className="required">*</span>
                </label>
                <input
                  type="password"
                  id="password"
                  name="password"
                  value={formData.password}
                  onChange={handleChange}
                  className={errors.password ? 'error' : ''}
                  placeholder="Enter your password"
                  aria-describedby={errors.password ? 'password-error' : undefined}
                />
                {errors.password && (
                  <span className="error-message" id="password-error" role="alert">
                    {errors.password}
                  </span>
                )}
              </div>

              <button
                type="submit"
                className="btn btn-primary btn-block"
                disabled={loading}
              >
                {loading ? 'Logging in...' : 'Login'}
              </button>
            </form>

            <div className="auth-footer">
              <p>
                Don't have an account?{' '}
                <Link to="/auth/signup" className="auth-link">
                  Sign up here
                </Link>
              </p>
            </div>

            <div className="auth-demo">
              <p className="demo-title">Demo Credentials:</p>
              <p className="demo-creds">
                Email: <code>demo@ticket.app</code><br />
                Password: <code>password123</code>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
