// react/src/components/Navbar.jsx
import { Link, useNavigate } from 'react-router-dom';
import { isAuthenticated, logout, getCurrentUser } from '../utils/auth';
import toast from 'react-hot-toast';
import { useState } from 'react';

const Navbar = () => {
  const navigate = useNavigate();
  const authenticated = isAuthenticated();
  const user = getCurrentUser();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const handleLogout = () => {
    logout();
    toast.success('Logged out successfully');
    navigate('/');
    setMobileMenuOpen(false);
  };

  const toggleMobileMenu = () => {
    setMobileMenuOpen(!mobileMenuOpen);
  };

  return (
    <nav className="navbar">
      <div className="container">
        <div className="nav-content">
          <Link to="/" className="logo" onClick={() => setMobileMenuOpen(false)}>
            🎫 TicketApp
          </Link>

          {/* Mobile Menu Button */}
          <button 
            className="mobile-menu-btn" 
            onClick={toggleMobileMenu}
            aria-label="Toggle menu"
          >
            {mobileMenuOpen ? '✕' : '☰'}
          </button>

          {/* Navigation Links */}
          <div className={`nav-links ${mobileMenuOpen ? 'mobile-open' : ''}`}>
            {authenticated ? (
              <>
                <Link 
                  to="/dashboard" 
                  className="nav-link"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Dashboard
                </Link>
                <Link 
                  to="/tickets" 
                  className="nav-link"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Tickets
                </Link>
                <span className="nav-user">👤 {user?.name}</span>
                <button onClick={handleLogout} className="btn btn-secondary">
                  Logout
                </button>
              </>
            ) : (
              <>
                <Link 
                  to="/auth/login" 
                  className="btn btn-secondary"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Login
                </Link>
                <Link 
                  to="/auth/signup" 
                  className="btn btn-primary"
                  onClick={() => setMobileMenuOpen(false)}
                >
                  Get Started
                </Link>
              </>
            )}
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// stage2/vue/src/components/Navbar.vue
<template>
  <nav class="navbar">
    <div class="container">
      <div class="nav-content">
        <router-link to="/" class="logo" @click="closeMobileMenu">
          🎫 TicketApp
        </router-link>

        <button 
          class="mobile-menu-btn" 
          @click="toggleMobileMenu"
          aria-label="Toggle menu"
        >
          {{ mobileMenuOpen ? '✕' : '☰' }}
        </button>

        <div :class="['nav-links', { 'mobile-open': mobileMenuOpen }]">
          <template v-if="authenticated">
            <router-link 
              to="/dashboard" 
              class="nav-link"
              @click="closeMobileMenu"
            >
              Dashboard
            </router-link>
            <router-link 
              to="/tickets" 
              class="nav-link"
              @click="closeMobileMenu"
            >
              Tickets
            </router-link>
            <span class="nav-user">👤 {{ user?.name }}</span>
            <button @click="handleLogout" class="btn btn-secondary">
              Logout
            </button>
          </template>
          <template v-else>
            <router-link 
              to="/auth/login" 
              class="btn btn-secondary"
              @click="closeMobileMenu"
            >
              Login
            </router-link>
            <router-link 
              to="/auth/signup" 
              class="btn btn-primary"
              @click="closeMobileMenu"
            >
              Get Started
            </router-link>
          </template>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'vue-toastification'
import { isAuthenticated, logout, getCurrentUser } from '../utils/auth'

const router = useRouter()
const toast = useToast()
const mobileMenuOpen = ref(false)

const authenticated = computed(() => isAuthenticated())
const user = computed(() => getCurrentUser())

const toggleMobileMenu = () => {
  mobileMenuOpen.value = !mobileMenuOpen.value
}

const closeMobileMenu = () => {
  mobileMenuOpen.value = false
}

const handleLogout = () => {
  logout()
  toast.success('Logged out successfully')
  router.push('/')
  closeMobileMenu()
}
</script>
